/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module spi_slave_sclk(rstn, sclk, cs_n, dis, sdio_in, sdio_out, sdio_oe, tx_data, rx_data, data_oe, byte_end);
  wire sclk_buf;
  wire cs_n_buf;
  wire sdio_in_buf;
  wire _00_;
  wire [7:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire [2:0] _33_;
  wire [2:0] _34_;
  wire [2:0] bit_cnt;
  output byte_end;
  wire byte_end;
  wire cnt_rstn;
  input cs_n;
  wire cs_n;
  output data_oe;
  wire data_oe;
  input dis;
  wire dis;
  wire msb_done;
  input rstn;
  wire rstn;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  wire [7:0] rx_data_r;
  input sclk;
  wire sclk;
  input sdio_in;
  wire sdio_in;
  output sdio_oe;
  wire sdio_oe;
  output sdio_out;
  wire sdio_out;
  wire shift_clk;
  wire [7:0] sr;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  INV_X1 _35_ (
    .A(dis),
    .Y(data_oe)
  );
  INV_X1 _36_ (
    .A(rstn),
    .Y(_12_)
  );
  NOR4 _37_ (
    .A(_33_[0]),
    .B(_03_),
    .C(_02_),
    .D(cs_n_buf),
    .Y(byte_end)
  );
  AND2_X1 _38_ (
    .A(data_oe),
    .B(byte_end),
    .Y(_13_)
  );
  OR3 _47_ (
    .A(bit_cnt[2]),
    .B(bit_cnt[0]),
    .C(bit_cnt[1]),
    .Y(_00_)
  );
  MUX2 _48_ (
    .A(tx_data[7]),
    .B(sr[7]),
    .S(msb_done),
    .Y(sdio_out)
  );
  AND2_X1 _49_ (
    .A(sdio_in_buf),
    .B(data_oe),
    .Y(_01_[0])
  );
  NOR4 _50_ (
    .A(bit_cnt[2]),
    .B(_33_[0]),
    .C(bit_cnt[1]),
    .D(data_oe),
    .Y(_14_)
  );
  NOR2 _58_ (
    .A(cs_n_buf),
    .B(_12_),
    .Y(cnt_rstn)
  );
  XOR2 _59_ (
    .A(dis),
    .B(sclk_buf),
    .Y(shift_clk)
  );
  NOR2 _60_ (
    .A(cs_n_buf),
    .B(data_oe),
    .Y(sdio_oe)
  );
  NAND2 _61_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_15_)
  );
  XOR2 _62_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_34_[1])
  );
  XNOR2 _63_ (
    .A(bit_cnt[2]),
    .B(_15_),
    .Y(_34_[2])
  );
  MUXDFFRB _64_ (.A(rx_data_r[0]), .B(sdio_in_buf), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[0]), .QB(_22_));
  MUXDFFRB _65_ (.A(rx_data_r[1]), .B(sr[0]), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[1]), .QB(_21_));
  MUXDFFRB _66_ (.A(rx_data_r[2]), .B(sr[1]), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[2]), .QB(_20_));
  MUXDFFRB _67_ (.A(rx_data_r[3]), .B(sr[2]), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[3]), .QB(_19_));
  MUXDFFRB _68_ (.A(rx_data_r[4]), .B(sr[3]), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[4]), .QB(_18_));
  MUXDFFRB _69_ (.A(rx_data_r[5]), .B(sr[4]), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[5]), .QB(_17_));
  MUXDFFRB _70_ (.A(rx_data_r[6]), .B(sr[5]), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[6]), .QB(_16_));
  MUXDFFRB _71_ (.A(rx_data_r[7]), .B(sr[6]), .S(_13_), .CK(sclk_buf), .RSTB(rstn), .Q(rx_data_r[7]), .QB(_23_));
  DFFRB _72_ (
    .CK(shift_clk),
    .D(_00_),
    .Q(msb_done),
    .QB(_24_),
    .RSTB(cnt_rstn)
  );
  DFFRB _73_ (
    .CK(shift_clk),
    .D(_01_[0]),
    .Q(sr[0]),
    .QB(_25_),
    .RSTB(rstn)
  );
  MUXDFFRB _74_ (.A(sr[0]), .B(tx_data[0]), .S(_14_), .CK(shift_clk), .RSTB(rstn), .Q(sr[1]), .QB(_26_));
  MUXDFFRB _75_ (.A(sr[1]), .B(tx_data[1]), .S(_14_), .CK(shift_clk), .RSTB(rstn), .Q(sr[2]), .QB(_27_));
  MUXDFFRB _76_ (.A(sr[2]), .B(tx_data[2]), .S(_14_), .CK(shift_clk), .RSTB(rstn), .Q(sr[3]), .QB(_28_));
  MUXDFFRB _77_ (.A(sr[3]), .B(tx_data[3]), .S(_14_), .CK(shift_clk), .RSTB(rstn), .Q(sr[4]), .QB(_29_));
  MUXDFFRB _78_ (.A(sr[4]), .B(tx_data[4]), .S(_14_), .CK(shift_clk), .RSTB(rstn), .Q(sr[5]), .QB(_30_));
  MUXDFFRB _79_ (.A(sr[5]), .B(tx_data[5]), .S(_14_), .CK(shift_clk), .RSTB(rstn), .Q(sr[6]), .QB(_31_));
  MUXDFFRB _80_ (.A(sr[6]), .B(tx_data[6]), .S(_14_), .CK(shift_clk), .RSTB(rstn), .Q(sr[7]), .QB(_32_));
  DFFRB _81_ (
    .CK(sclk_buf),
    .D(_33_[0]),
    .Q(bit_cnt[0]),
    .QB(_33_[0]),
    .RSTB(cnt_rstn)
  );
  DFFRB _82_ (
    .CK(sclk_buf),
    .D(_34_[1]),
    .Q(bit_cnt[1]),
    .QB(_03_),
    .RSTB(cnt_rstn)
  );
  DFFRB _83_ (
    .CK(sclk_buf),
    .D(_34_[2]),
    .Q(bit_cnt[2]),
    .QB(_02_),
    .RSTB(cnt_rstn)
  );
  assign _33_[2:1] = bit_cnt[2:1];
  assign _34_[0] = _33_[0];
  assign rx_data = rx_data_r;
  BUFTH u_bufth_sclk (.A(sclk), .Y(sclk_buf));
  BUFTH u_bufth_cs_n (.A(cs_n), .Y(cs_n_buf));
  BUFTH u_bufth_sdio_in (.A(sdio_in), .Y(sdio_in_buf));
endmodule
