#!/usr/bin/env python3
"""gen_liberty.py -- build a Liberty file for TR1um_5_stdcell from measured data.

Generalised from TR-1um_Async_I2C/script/gen_liberty.py.  That version carried
its cell table inline and used `area: 1` relative placeholders; this one reads
lef/cell_info.json, whose areas are the real cell bounding boxes measured from
lef/TR-1um_STDCELL.gds and whose transistor counts come from the cells'
extracted SPICE.  Synthesis therefore optimises for the true silicon area and
gate_count.py's numbers agree with what ABC saw.

TIMING IS STILL A PLACEHOLDER -- fixed 1x1 NLDM tables, present only so ABC's
Liberty reader accepts the file.  NOT characterised; do not use for STA.

  usage:  scripts/gen_liberty.py [-o lef/TR1um_5_stdcell_area.lib]
"""
import argparse
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INFO = os.path.join(ROOT, "lef", "cell_info.json")
OUT = os.path.join(ROOT, "lef", "TR1um_5_stdcell_area.lib")

HEADER = """/* TR1um_5_stdcell_area.lib -- generated by scripts/gen_liberty.py
 *
 * area  : REAL, measured from lef/TR-1um_STDCELL.gds cell bounding boxes.
 * timing: PLACEHOLDER, fixed tables so ABC accepts the file. NOT for STA.
 */
library (TR1um_5_stdcell_area) {
  technology (cmos);
  delay_model : table_lookup;
  time_unit : "1ns";
  voltage_unit : "1V";
  current_unit : "1mA";
  capacitive_load_unit (1, pf);
  pulling_resistance_unit : "1kohm";
  leakage_power_unit : "1nW";
  default_input_pin_cap : 0.01;
  default_output_pin_cap : 0.0;
  default_inout_pin_cap : 0.01;
  default_fanout_load : 1.0;
  default_max_transition : 20.0;
  nom_voltage : 5.0;
  nom_temperature : 25.0;
  nom_process : 1.0;

  lu_table_template (scalar) {
    variable_1 : total_output_net_capacitance;
    index_1 ("0.0");
  }
"""


def tim(rel, d="0.5", ttype=None):
    s = '        timing () {\n          related_pin : "%s";\n' % rel
    if ttype:
        s += "          timing_type : %s;\n" % ttype
    s += ('          cell_rise (scalar) { values ("%s"); }\n'
          '          cell_fall (scalar) { values ("%s"); }\n'
          '          rise_transition (scalar) { values ("0.10"); }\n'
          '          fall_transition (scalar) { values ("0.10"); }\n'
          "        }\n" % (d, d))
    return s


def comb(name, c):
    s = "\n  cell (%s) {\n    area : %d;\n" % (name, c["area_um2"])
    s += "    /* %.1f x %.1f um, %s transistors */\n" % (
        c["width_um"], c["height_um"], c["transistors"])
    for p in c["in_pins"]:
        s += "    pin (%s) { direction : input; capacitance : 0.01; }\n" % p
    s += ('    pin (%s) {\n      direction : output;\n      function : "%s";\n'
          "      max_capacitance : 1.0;\n" % (c["out_pin"], c["function"]))
    for p in c["in_pins"]:
        s += tim(p)
    return s + "    }\n  }\n"


def dffrb(name, c):
    s = "\n  cell (%s) {\n    area : %d;\n" % (name, c["area_um2"])
    s += "    /* %.1f x %.1f um, %s transistors -- async active-low reset */\n" % (
        c["width_um"], c["height_um"], c["transistors"])
    s += """    ff (IQ, IQN) {
      next_state : "D";
      clocked_on : "CK";
      clear : "RSTB'";
    }
    pin (D) { direction : input; capacitance : 0.01;
      timing () { related_pin : "CK"; timing_type : setup_rising;
        rise_constraint (scalar) { values ("0.3"); }
        fall_constraint (scalar) { values ("0.3"); } }
      timing () { related_pin : "CK"; timing_type : hold_rising;
        rise_constraint (scalar) { values ("0.1"); }
        fall_constraint (scalar) { values ("0.1"); } } }
    pin (CK)   { direction : input; capacitance : 0.02; clock : true; }
    pin (RSTB) { direction : input; capacitance : 0.01; }
"""
    s += '    pin (Q) { direction : output; function : "IQ";\n'
    s += tim("CK", "0.8", "rising_edge") + "    }\n"
    s += '    pin (QB) { direction : output; function : "IQN";\n'
    s += tim("CK", "0.8", "rising_edge") + "    }\n  }\n"
    return s


def main(info_path=INFO, out_path=OUT, skip=()):
    info = json.load(open(info_path))
    out = [HEADER]
    n = 0
    for name, c in sorted(info.items()):
        if name.startswith("_") or name in skip:
            continue
        if c["kind"] == "comb":
            out.append(comb(name, c)); n += 1
        elif name == "DFFRB":
            out.append(dffrb(name, c)); n += 1
        # MUXDFFRB is created by scripts/merge_muxdffrb.py after mapping, and
        # RSLATCH/DFFS/physical cells are not synthesis targets -- omitted so
        # ABC never picks something the merge pass cannot account for.
    out.append("}\n")
    open(out_path, "w").write("".join(out))
    print("wrote %s (%d cells)" % (out_path, n))
    return out_path


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-i", "--cell-info", default=INFO)
    ap.add_argument("-o", "--output", default=OUT)
    ap.add_argument("--skip", default="", help="comma-separated cells to omit")
    a = ap.parse_args()
    main(a.cell_info, a.output,
         tuple(s.strip() for s in a.skip.split(",") if s.strip()))
