#!/usr/bin/env python3
"""gen_cell_spice.py -- build lef/TR-1um_STDCELL.spice, the project's
schematic-side transistor-level standard-cell library.

WHY THIS EXISTS
---------------
The LVS reference netlist has to be a *schematic-side* description of every
placed cell.  The I2C project took those bodies from xschem's own per-cell
exports under ~/.xschem/simulations/ (see scripts/i2c_ref/gen_lvs_spice_v10.py),
a directory that lives outside any repository and is not reachable from this
project.  Rather than hand-copy transistors -- the one thing an LVS reference
must never be -- this script lifts each cell's `.subckt ... .ends` block
verbatim out of

    TR-1um_I2C_2026/src/tr_1um_i2c_slave_async.cir

which is the *as-submitted* chip-level LVS netlist of the I2C MPW entry: the
same standard-cell library, and one that a real KLayout LVS run has already
matched device-for-device against the same lef/TR-1um_STDCELL.gds this project
uses (design_notes.md 108.51).  That makes it the strongest available source.
Override the path with $I2C_REF_CIR if the sibling checkout lives elsewhere.

The output file IS checked in, so the project stays self-contained and this
script only has to be re-run when the cell library itself changes.

CELLS NOT IN THE I2C NETLIST
----------------------------
BUF_X2 is new in this project (added to lef/TR-1um_STDCELL.gds this session),
so the I2C .cir has no body for it and one is defined below.  It is *not* a
transcription of the layout: BUF_X2 is by construction BUF_X1 with a second
output-stage inverter wired in parallel, which is what the "X2" drive means.
scripts/check_cell_spice.py then checks that definition against the real GDS
geometry independently.

  NOTE: lef/BUF_X2.sch as shipped by the user describes only FOUR transistors
  -- it is a copy of BUF_X1's schematic -- while the DRC-clean BUF_X2 in
  lef/TR-1um_STDCELL.gds has SIX (3 PMOS fingers of W=10.2u, 3 NMOS of
  W=3.4u).  That schematic would fail LVS; see design_notes.md.

TAP2 has no transistors at all (well/substrate taps only) and therefore gets no
subckt -- it simply contributes nothing to the netlist.  FILL3 likewise has no
subckt here: like the I2C flow, its two decap devices are emitted inline in the
top cell by gen_lvs_spice.py, because that is how the layout extracts them.

  usage:  scripts/gen_cell_spice.py [--check]
"""
import argparse
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
import spi_config as _cfg

OUT_PATH = os.path.join(_cfg.ROOT, "lef", "TR-1um_STDCELL.spice")

DEFAULT_REF_CIR = os.path.join(
    os.path.dirname(_cfg.ROOT), "TR-1um_I2C_2026", "src", "tr_1um_i2c_slave_async.cir"
)
REF_CIR = os.environ.get("I2C_REF_CIR", DEFAULT_REF_CIR)

# What the generated file records as the source.  Deliberately NOT the absolute
# path: that differs between machines (and between a sandbox and the user's
# disk), which would make --check report a spurious "out of date".
REF_LABEL = "TR-1um_I2C_2026/src/" + os.path.basename(REF_CIR)

# Cells that the .cir does not define and this project has to supply itself.
# Keep every one of these justified in the module docstring.
LOCAL_BODIES = {
    "BUF_X2": """.subckt BUF_X2 VDD A Y GND
*.PININFO A:I Y:O VDD:B GND:B
* BUF_X1's input inverter ...
MM7 net1 A VDD VDD PMOS w=10.2u l=1u
MM3 net1 A GND GND NMOS w=3.4u l=1u
* ... driving two output inverters in parallel (that is the "X2").
MM1 Y net1 VDD VDD PMOS w=10.2u l=1u
MM2 Y net1 GND GND NMOS w=3.4u l=1u
MM4 Y net1 VDD VDD PMOS w=10.2u l=1u
MM5 Y net1 GND GND NMOS w=3.4u l=1u
.ends""",
}

# Cells that are placed but contribute no .subckt.  Documented above.
NO_DEVICE_CELLS = {"TAP2"}
INLINE_DECAP_CELLS = {"FILL3"}

HEADER = """** TR-1um_STDCELL.spice -- schematic-side transistor-level bodies for the
** standard cells this project places.  GENERATED by scripts/gen_cell_spice.py;
** do not edit by hand.
**
** Source for every cell marked "from I2C .cir":
**   {ref}
** (the as-submitted TR-1um_I2C_2026 chip LVS netlist -- same cell library,
** already matched device-for-device against lef/TR-1um_STDCELL.gds by a real
** KLayout LVS run).  Bodies are copied verbatim, never retyped.
**
** TAP2 has no devices and no subckt.  FILL3's decap pair is emitted inline in
** the top cell by scripts/gen_lvs_spice.py, matching the layout extraction.
"""


def parse_subckts(text):
    """Return {name: (decl_pins, [lines including .subckt/.ends])}."""
    out = {}
    cur = None
    buf = []
    for line in text.splitlines():
        s = line.strip()
        if s.lower().startswith(".subckt "):
            cur = s.split()[1]
            buf = [line]
        elif cur is not None:
            buf.append(line)
            if s.lower().startswith(".ends"):
                out[cur] = (buf[0].split()[2:], list(buf))
                cur = None
    return out


def used_cell_types():
    """Every cell type instantiated by the netlist, plus the fill/tap cells the
    placement adds."""
    import json
    text = open(_cfg.NET_PATH).read()
    skip = {"module", "endmodule", "input", "output", "wire", "assign", "reg", "inout"}
    types = set()
    for m in re.finditer(
        r"^\s*([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*\(\s*(.*?)\)\s*;", text, re.M | re.S
    ):
        if m.group(1) not in skip:
            types.add(m.group(1))
    placement = json.load(open(_cfg.PLACEMENT_JSON))
    for row in placement["rows"]:
        for inst in row:
            types.add(inst["type"])
    return types


def build():
    ref_text = open(REF_CIR).read()
    ref = parse_subckts(ref_text)

    types = used_cell_types()
    wanted = sorted(t for t in types if t not in NO_DEVICE_CELLS and t not in INLINE_DECAP_CELLS)

    missing = [t for t in wanted if t not in ref and t not in LOCAL_BODIES]
    if missing:
        raise SystemExit(
            f"no transistor-level body available for {missing} -- neither in\n"
            f"  {REF_CIR}\n"
            f"nor in this script's LOCAL_BODIES"
        )

    chunks = [HEADER.format(ref=REF_LABEL)]
    for typ in wanted:
        if typ in ref:
            chunks.append(f"** {typ}: from I2C .cir\n" + "\n".join(ref[typ][1]))
        else:
            chunks.append(f"** {typ}: defined locally (see gen_cell_spice.py)\n" + LOCAL_BODIES[typ])
    return "\n\n".join(chunks) + "\n", wanted


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report whether the checked-in file is up to date; write nothing")
    args = ap.parse_args()

    content, wanted = build()
    if args.check:
        old = open(OUT_PATH).read() if os.path.exists(OUT_PATH) else None
        if old == content:
            print(f"up to date: {OUT_PATH} ({len(wanted)} cell bodies)")
        else:
            print(f"OUT OF DATE: {OUT_PATH}")
            raise SystemExit(1)
        return

    with open(OUT_PATH, "w") as f:
        f.write(content)
    local = sorted(set(wanted) & set(LOCAL_BODIES))
    print(f"wrote {OUT_PATH}: {len(wanted)} cell body(ies) "
          f"({len(wanted) - len(local)} from {os.path.basename(REF_CIR)}, "
          f"{len(local)} local: {local})")


if __name__ == "__main__":
    main()
